scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: prometheus
  scrape_interval: 5s
  static_configs:
    - targets: ['localhost:9090']

- job_name: telegraf
  scrape_interval: 5s
  static_configs:
    - targets:
      - telegraf:9273